function makeVideoSprite(tag, videoPath,camera,zoom)
    amieven = getProperty('camZooming')
    startVideo(videoPath, false, true, false)
    setObjectCamera('videoCutscene',camera)
    screenCenter(videoPath)
    setProperty("camZooming", true)
    setProperty('camGame.zoom',zoom)
    setProperty('defaultCamZoom',zoom)
    setProperty("camZooming", amieven)
end